services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    networks:
      - note-taking-network
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app
    env_file:
      - ./dotenv_files/.env
    networks:
      - note-taking-network
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:

networks:
  note-taking-network: